server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orion?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:user_1}
    password: ${SPRING_DATASOURCE_PASSWORD:abc@1234}

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload.dir}

file:
  upload:
    dir: ./uploads
